// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3vu1s-d7-8vHSmqEPHEnS4ishl2CJajY',
    appId: '1:633986399795:web:89e9fadef0853a6ef6ad46',
    messagingSenderId: '633986399795',
    projectId: 'buildcare-2f1bb',
    authDomain: 'buildcare-2f1bb.firebaseapp.com',
    storageBucket: 'buildcare-2f1bb.firebasestorage.app',
    measurementId: 'G-FKBRTP4QCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACJIVBfhvuK76yn8CY6u-JaQj_Zlch9g0',
    appId: '1:633986399795:android:0b23279ab906be00f6ad46',
    messagingSenderId: '633986399795',
    projectId: 'buildcare-2f1bb',
    storageBucket: 'buildcare-2f1bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnRJ-sXMQmxjxTK3KdDqyKSKnBrAXONo8',
    appId: '1:633986399795:ios:ca1bf8aaecba2441f6ad46',
    messagingSenderId: '633986399795',
    projectId: 'buildcare-2f1bb',
    storageBucket: 'buildcare-2f1bb.firebasestorage.app',
    iosBundleId: 'com.example.buildcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnRJ-sXMQmxjxTK3KdDqyKSKnBrAXONo8',
    appId: '1:633986399795:ios:ca1bf8aaecba2441f6ad46',
    messagingSenderId: '633986399795',
    projectId: 'buildcare-2f1bb',
    storageBucket: 'buildcare-2f1bb.firebasestorage.app',
    iosBundleId: 'com.example.buildcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3vu1s-d7-8vHSmqEPHEnS4ishl2CJajY',
    appId: '1:633986399795:web:2c86c75affc39fd2f6ad46',
    messagingSenderId: '633986399795',
    projectId: 'buildcare-2f1bb',
    authDomain: 'buildcare-2f1bb.firebaseapp.com',
    storageBucket: 'buildcare-2f1bb.firebasestorage.app',
    measurementId: 'G-H20Q3PG2QY',
  );
}
