import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

// --- Main Function to Initialize Firebase and Run the App ---
void main() async {
  // Ensure Flutter is initialized before using plugins
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // Run the application
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firebase Signup Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        // Define a consistent input decoration theme for text fields
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: Colors.grey[200],
          contentPadding:
              const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide.none,
          ),
          hintStyle: TextStyle(color: Colors.grey[500]),
        ),
      ),
      home: const SignUpScreen(),
    );
  }
}

// --- The Main SignUp Screen Widget ---
class SignUpScreen extends StatefulWidget {
  const SignUpScreen({super.key});

  @override
  State<SignUpScreen> createState() => _SignUpScreenState();
}

class _SignUpScreenState extends State<SignUpScreen> {
  // Global key to validate the form
  final _formKey = GlobalKey<FormState>();

  // Text editing controllers for each field
  final _nameController = TextEditingController();
  final _nicController = TextEditingController();
  final _emailController = TextEditingController();
  final _officePhoneController = TextEditingController();
  final _mobileController = TextEditingController();
  final _petNameController = TextEditingController();
  final _nicknameController = TextEditingController();
  final _passwordController = TextEditingController();
  final _confirmPasswordController = TextEditingController();

  // Dropdown values
  String? _selectedUserType;
  String? _selectedOffice;

  // For password visibility toggles
  bool _isPasswordObscured = true;
  bool _isConfirmPasswordObscured = true;
  bool _isLoading = false;

  // Dropdown list items
  final List<String> _userTypes = [
    'Provincial Engineer',
    'Site Manager',
    'Contractor'
  ];
  final List<String> _offices = ['Matara', 'Galle', 'Colombo', 'Kandy'];

  @override
  void dispose() {
    // Dispose controllers to free up resources
    _nameController.dispose();
    _nicController.dispose();
    _emailController.dispose();
    _officePhoneController.dispose();
    _mobileController.dispose();
    _petNameController.dispose();
    _nicknameController.dispose();
    _passwordController.dispose();
    _confirmPasswordController.dispose();
    super.dispose();
  }

  // --- The Signup Logic ---
  Future<void> _signUp() async {
    // Validate the form first
    if (!_formKey.currentState!.validate()) {
      return;
    }

    // Check if passwords match
    if (_passwordController.text != _confirmPasswordController.text) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text("Passwords do not match!")),
      );
      return;
    }

    setState(() {
      _isLoading = true; // Show loading indicator
    });

    try {
      // 1. Create user in Firebase Authentication
      final UserCredential userCredential =
          await FirebaseAuth.instance.createUserWithEmailAndPassword(
        email: _emailController.text.trim(),
        password: _passwordController.text.trim(),
      );

      // 2. Store additional user data in Firestore
      if (userCredential.user != null) {
        final String uid = userCredential.user!.uid;
        await FirebaseFirestore.instance.collection('users').doc(uid).set({
          'uid': uid,
          'userType': _selectedUserType,
          'name': _nameController.text.trim(),
          'nic': _nicController.text.trim(),
          'office': _selectedOffice,
          'email': _emailController.text.trim(),
          'officePhone': _officePhoneController.text.trim(),
          'mobilePhone': _mobileController.text.trim(),
          'securityQuestionPet': _petNameController.text.trim(),
          'securityQuestionNickname': _nicknameController.text.trim(),
          'createdAt': Timestamp.now(),
        });

        // Show success message
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text("Registration Successful!")),
        );
        // You can navigate to another screen here
        // Navigator.of(context).pushReplacement(...);
      }
    } on FirebaseAuthException catch (e) {
      // Handle specific Firebase Auth errors
      String message = 'An error occurred. Please try again.';
      if (e.code == 'weak-password') {
        message = 'The password provided is too weak.';
      } else if (e.code == 'email-already-in-use') {
        message = 'An account already exists for that email.';
      }
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(message)),
      );
    } catch (e) {
      // Handle other errors
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Failed to register: ${e.toString()}')),
      );
    } finally {
      setState(() {
        _isLoading = false; // Hide loading indicator
      });
    }
  }

  // --- Building the UI ---
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24.0),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                const SizedBox(height: 20),
                const Text(
                  'Create an Account',
                  textAlign: TextAlign.center,
                  style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 30),

                // -- Dropdowns and TextFields --
                _buildDropdown('User Type', _userTypes, _selectedUserType,
                    (value) {
                  setState(() => _selectedUserType = value);
                }),
                const SizedBox(height: 16),
                _buildTextField(
                    _nameController, "Engineer's Name", Icons.person_outline),
                const SizedBox(height: 16),
                _buildTextField(_nicController, "NIC Number", null),
                const SizedBox(height: 16),
                _buildDropdown('Select Your Office', _offices, _selectedOffice,
                    (value) {
                  setState(() => _selectedOffice = value);
                }),
                const SizedBox(height: 16),
                _buildTextField(_emailController, "Email", Icons.email_outlined,
                    keyboardType: TextInputType.emailAddress),
                const SizedBox(height: 16),
                _buildTextField(
                    _officePhoneController, "Office Phone Number", null,
                    keyboardType: TextInputType.phone),
                const SizedBox(height: 16),
                _buildTextField(_mobileController, "Mobile Number",
                    Icons.phone_android_outlined,
                    keyboardType: TextInputType.phone),
                const SizedBox(height: 16),
                _buildTextField(_petNameController, "First Pet Name", null),
                const SizedBox(height: 16),
                _buildTextField(
                    _nicknameController, "Childhood nickname", null),
                const SizedBox(height: 16),
                _buildPasswordField(_passwordController, "Enter Your Password",
                    _isPasswordObscured, () {
                  setState(() => _isPasswordObscured = !_isPasswordObscured);
                }),
                const SizedBox(height: 16),
                _buildPasswordField(_confirmPasswordController,
                    "Enter Password Again", _isConfirmPasswordObscured, () {
                  setState(() =>
                      _isConfirmPasswordObscured = !_isConfirmPasswordObscured);
                }),
                const SizedBox(height: 30),

                // -- Sign Up Button --
                _isLoading
                    ? const Center(child: CircularProgressIndicator())
                    : ElevatedButton(
                        onPressed: _signUp,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: Colors.blueAccent,
                          foregroundColor: Colors.white,
                          padding: const EdgeInsets.symmetric(vertical: 16),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                        child: const Text('Sign Up',
                            style: TextStyle(fontSize: 18)),
                      ),
                const SizedBox(height: 20),

                // -- Sign In Link --
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Text("Already Registered?"),
                    TextButton(
                      onPressed: () {
                        // TODO: Navigate to Sign In screen
                      },
                      child: const Text('Sign in'),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  // --- Helper Widgets for Building Form Fields ---

  Widget _buildTextField(
      TextEditingController controller, String label, IconData? icon,
      {TextInputType? keyboardType}) {
    return TextFormField(
      controller: controller,
      keyboardType: keyboardType,
      decoration: InputDecoration(
        hintText: label,
        prefixIcon: icon != null ? Icon(icon, color: Colors.grey[600]) : null,
      ),
      validator: (value) {
        if (value == null || value.isEmpty) {
          return 'Please enter your $label';
        }
        if (label == "Email" && !RegExp(r'\S+@\S+\.\S+').hasMatch(value)) {
          return 'Please enter a valid email address';
        }
        return null;
      },
    );
  }

  Widget _buildPasswordField(TextEditingController controller, String label,
      bool isObscured, VoidCallback toggleVisibility) {
    return TextFormField(
      controller: controller,
      obscureText: isObscured,
      decoration: InputDecoration(
        hintText: label,
        suffixIcon: IconButton(
          icon: Icon(isObscured
              ? Icons.visibility_off_outlined
              : Icons.visibility_outlined),
          onPressed: toggleVisibility,
        ),
      ),
      validator: (value) {
        if (value == null || value.isEmpty) {
          return 'Please enter a password';
        }
        if (value.length < 6) {
          return 'Password must be at least 6 characters long';
        }
        return null;
      },
    );
  }

  Widget _buildDropdown(String hint, List<String> items, String? selectedValue,
      ValueChanged<String?> onChanged) {
    return DropdownButtonFormField<String>(
      decoration: InputDecoration(
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      ),
      initialValue: selectedValue,
      hint: Text(hint, style: TextStyle(color: Colors.grey[600])),
      isExpanded: true,
      items: items.map((String value) {
        return DropdownMenuItem<String>(
          value: value,
          child: Text(value),
        );
      }).toList(),
      onChanged: onChanged,
      validator: (value) => value == null ? 'Please select a $hint' : null,
    );
  }
}
